In [1]:
import numpy as np

### numpy array

In [3]:
# burada tek boyutlu ya da iki boyutlu diziler kullanabiliyoruz.

In [8]:
# normal bir list'i numpy array'e dönüştürmek için
myList = [10, 20, 30, 40]
np.array(myList) # bunu yapmak yeterli olacaktır, type'ına bakınca numpy'ın içerisinden bir nesne olduğunu görüyoruz

array([10, 20, 30, 40])

In [9]:
matrixList = [[10,20,30], [20, 30, 40], [30, 40, 50]]

In [10]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

### arange

In [11]:
list(range(0,10)) # range ile bu şekilde liste oluşturabiliyorduk

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(0, 10) # numpy ile array oluşturma

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 10, 2) # başlangıç, bitiş, stepsize

array([0, 2, 4, 6, 8])

### zeros - ones

In [15]:
np.zeros(5) # Sıfırlardan oluşan bir dizi oluşturuyor

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,2)) # Çok boyutlu 

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones((3,3)) # Birlerden oluşan bir dizi oluşturur

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

Belirlediğimiz aralıkta, eşit olarak boyutlandırılmış, aralık bırakılmış şekilde dizi oluşturmaya yarar.

In [18]:
np.linspace(0,20,5) # 0-20 arasında eşit aralıklı 5 sayı olacak

array([ 0.,  5., 10., 15., 20.])

### eye

Identity matrix oluşturur.

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random

Normal dağılıma uygun random veriler üretir, numpy'ın kendi içerisinde var.

In [20]:
np.random.randn(8)  

array([ 0.16261656, -0.95162482,  0.31671057,  0.03381001,  2.66634003,
       -0.53116627, -0.38645614,  0.45240136])

In [22]:
np.random.randn(4,4)

array([[ 0.59121758, -0.66143203, -0.92969513,  0.29864862],
       [ 0.80008145,  0.56546547,  0.11802466,  0.11270036],
       [-0.98019764, -1.40863117,  0.06006333,  0.29948045],
       [ 0.87595868,  0.40773196,  0.11368189, -0.25083896]])

In [23]:
np.random.randint(0, 10) # bu aralıkta int bir değer döndürecek, sonuncuyu almaz

6

In [25]:
np.random.randint(0, 10, 5) # dizi olması için, son parametre kaç tane sayı olduğunu belirtir, dizi elemanları random

array([8, 5, 9, 8, 7])

In [26]:
# Değişkene eşitlenebilir
myNumpyArray = np.arange(30)
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
myRandomArray = np.random.randint(0, 100, 20)
myRandomArray

array([26, 74, 68,  5, 51, 95, 73, 65, 61, 65, 31, 16, 32, 30, 76, 78, 60,
       17, 20, 47])

### numpy array metotları

In [29]:
# Array'lerin boyutlarında değişiklik yaparak matrix yapabiliriz
myNumpyArray.reshape(6, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [30]:
myNumpyArray.max() # maximum'u verir

29

In [33]:
# Bu şekilde max değeri bulabiliriz
myRandomArray.max() 

95

In [34]:
# Bu şekilde min değeri bulabiliriz
myRandomArray.min()

5

In [35]:
myRandomArray.argmax() # max elemanın kaçıncı index'te olduğunu verir

5

In [36]:
myRandomArray.argmin() # min kaçıncı index'te olduğunu verir

3

In [38]:
myNumpyArray.shape # sonunda () yok, metot ya da fonk. değil bir özellik. Array'in şeklini veriyor

(30,)