In [1]:
import numpy as np

In [2]:
myArray = np.arange(0, 15)

In [3]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
myArray[5] # 6. eleman,  listeyle aynı

5

In [7]:
myArray[3:5] # aynı listeler gibi hala

array([3, 4])

In [8]:
myArray[3:8] = -5 # bu elemanları -5 yapacak

In [9]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [10]:
anotherArray = np.arange(0,20)

In [11]:
anotherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
slicingArray = anotherArray[4:10] #slicingArray'deki değişiklikler anotherArray içini de değiştiriyor

In [17]:
slicingArray

array([700, 700, 700, 700, 700, 700])

In [18]:
slicingArray[:] = 700 # bu array'in bütün değerlerini 700 e eşitleyecek

In [19]:
slicingArray

array([700, 700, 700, 700, 700, 700])

In [20]:
anotherArray # buradan da gördüğümüz gibi yaptığımız değişiklik buraya yansını, numpy array'lere ait bir özellik

array([  0,   1,   2,   3, 700, 700, 700, 700, 700, 700,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [21]:
# Değişiklik olmasını istemezsek

In [22]:
sampleArray = np.arange(0, 20)

In [23]:
sampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
copySampleArray = sampleArray.copy() # kopyasını oluşturduk

In [25]:
copySampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
sampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
copySampleArraySlicing = copySampleArray[4:10]

In [28]:
copySampleArraySlicing[:] = 800

In [29]:
copySampleArraySlicing

array([800, 800, 800, 800, 800, 800])

In [30]:
copySampleArray

array([  0,   1,   2,   3, 800, 800, 800, 800, 800, 800,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [32]:
sampleArray # burda değişiklik olmadığını gördük, değişiklik olmasını istemiyorsak kopyayla işlem yapmak gerekiyor

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### matrix

In [33]:
myList = [[10,20,30],[20,30,40],[30,40,50]]

In [34]:
myMatrixArray = np.array(myList)

In [35]:
myMatrixArray

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [36]:
myMatrixArray[0]

array([10, 20, 30])

In [37]:
myMatrixArray[1][2]

40

In [38]:
myMatrixArray[1,2] # birinci sırayı, ikinci indexi veriyor

40

In [40]:
myMatrixArray[0:,2] # 0'dan itibaren kolonların 2. indexli elemanlarını verir

array([30, 40, 50])

In [41]:
myMatrixArray[1:, 1:]

array([[30, 40],
       [40, 50]])

In [42]:
newList = [[0,1,2,3,4],[5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19]]

In [43]:
newMatrix = np.array(newList)

In [44]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
newMatrix[[0,2,3]] #0, 2 ve 3. indexler dizi olarak gelecek

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
newMatrix[[3,2,1]] #index yerine liste vererek bir dizi oluşturuyoruz

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

### operasyonlar

In [49]:
anotherNewArray = np.random.randint(1,100,20)

In [50]:
anotherNewArray

array([98, 65, 92, 98, 25, 78, 85, 65,  7, 97, 94, 62, 62, 55, 40, 72, 84,
       35, 96, 72])

In [53]:
resultArray = anotherNewArray > 25 #25'den büyük olanları gösteriyor

In [54]:
resultArray

array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [55]:
anotherNewArray # diziyi değiştirmez bu

array([98, 65, 92, 98, 25, 78, 85, 65,  7, 97, 94, 62, 62, 55, 40, 72, 84,
       35, 96, 72])

In [56]:
anotherNewArray[resultArray] # İstediğimiz sonuçları filtreleyip bize dizi olarak veriyor

array([98, 65, 92, 98, 78, 85, 65, 97, 94, 62, 62, 55, 40, 72, 84, 35, 96,
       72])

In [57]:
anotherNewArray[anotherNewArray > 60] # şeklinde de yapılabilir

array([98, 65, 92, 98, 78, 85, 65, 97, 94, 62, 62, 72, 84, 96, 72])

In [58]:
finalArray = np.arange(0,20)

In [59]:
finalArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
finalArray + finalArray # elemanları toplayıp yazıyor

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [61]:
finalArray * finalArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [62]:
finalArray - finalArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
finalArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
finalArray / finalArray # 0:0 dan uyarı verir ama çalışır

<ipython-input-64-bdc15ac572a2>:1: RuntimeWarning: invalid value encountered in true_divide
  finalArray / finalArray # 0:0 dan uyarı verir ama çalışır


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [65]:
np.sqrt(finalArray) #karekökünü alıyor dizinin

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])